version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: project-md/server:latest
    ports:
      - '8081:8081'
    environment:
      - DB_NAME=mysql
    depends_on:
      - mysql
    
  mysql:
    image: mysql:8.0.28-oracle
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ksmin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: proj_md
